version: '3.8'

services:

  couchdb:
    image: couchdb
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - couchdata:/opt/couchdb/data

  app:
    build: .
    container_name: medapp
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - couchdb

volumes:
  couchdata: